language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

install:
  - yarn

script:
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $githubkey
  keep-history: true
  local-dir: dist
  repo: CIDR-Blocker/CIDR-Blocker.github.io
  target-branch: master
  on:
    branch: master
    